In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/dirty_customer_data (1).csv')
df

,CustomerID,Name,Age,Gender,City,JoinDate,PurchaseAmount,ProductCategory,Rating
0,118,Kiara Kumar,53,female,Chennai,11/01/2024,2625.28,FURNITURE,1.2
1,107,NaN,43,f,Banaras,2022/08/08,2954.49,Electronics,2.6
2,78,Saanvi Bose,45,male,HYDERABAD,20-Oct-2024,2984.16,electronics,3.7
3,93,ADITYA RAO,42,Male,Chennai,10-07-2021,1840.34,GROCERIES,1.0
4,18,Aadhya Singh,21,M,Mumbai,2024-08-14,3871.82,groceries,1.7
...,...,...,...,...,...,...,...,...,...
135,73,Aditya Bose,37,F,Hyderabad,09-Oct-2022,"₹3,708.85",Groceries,3.9
136,69,Riya Rao,57,Female,Banaras,2021-05-14,2763.77,Grocery,1.0
137,4,Arjun Iyer,NaN,female,BANGALORE,2024/12/15,"₹1,664.05",Groceries,3.8
138,120,MEERA MENON,33,NaN,HYDERABAD,2022-03-31,2575.75,Electronic,1.3
139,30,Ishaan Kumar,52,FEMALE,Chennai,2023/10/13,2130.66,Grocery,3.4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       140 non-null    int64
 1   Name             130 non-null    object
 2   Age              134 non-null    object
 3   Gender           133 non-null    object
 4   City             134 non-null    object
 5   JoinDate         131 non-null    object
 6   PurchaseAmount   135 non-null    object
 7   ProductCategory  136 non-null    object
 8   Rating           133 non-null    float64
dtypes: float64(1), int64(1), object(7)
memory usage: 10.0+ KB

**FINDING MISSING VALUES**

In [ ]:
df.isnull().sum()

CustomerID          0
Name               10
Age                 6
Gender              7
City                6
JoinDate            9
PurchaseAmount      5
ProductCategory     4
Rating              7
dtype: int64

**FINDING DUPLICATE RECORDS**

In [ ]:
df.duplicated().sum()

np.int64(16)

**Finding Incorrect Data Types**

In [ ]:
df.dtypes

CustomerID           int64
Name                object
Age                 object
Gender              object
City                object
JoinDate            object
PurchaseAmount      object
ProductCategory     object
Rating             float64
dtype: object

I AM MAKING COPY OF ORIGINAL DATA SO CLEANING PROCESS CAN BE PERFORMED ON IT

In [ ]:
c = df.copy()
c

,CustomerID,Name,Age,Gender,City,JoinDate,PurchaseAmount,ProductCategory,Rating
0,118,Kiara Kumar,53,female,Chennai,11/01/2024,2625.28,FURNITURE,1.2
1,107,NaN,43,f,Banaras,2022/08/08,2954.49,Electronics,2.6
2,78,Saanvi Bose,45,male,HYDERABAD,20-Oct-2024,2984.16,electronics,3.7
3,93,ADITYA RAO,42,Male,Chennai,10-07-2021,1840.34,GROCERIES,1.0
4,18,Aadhya Singh,21,M,Mumbai,2024-08-14,3871.82,groceries,1.7
...,...,...,...,...,...,...,...,...,...
135,73,Aditya Bose,37,F,Hyderabad,09-Oct-2022,"₹3,708.85",Groceries,3.9
136,69,Riya Rao,57,Female,Banaras,2021-05-14,2763.77,Grocery,1.0
137,4,Arjun Iyer,NaN,female,BANGALORE,2024/12/15,"₹1,664.05",Groceries,3.8
138,120,MEERA MENON,33,NaN,HYDERABAD,2022-03-31,2575.75,Electronic,1.3
139,30,Ishaan Kumar,52,FEMALE,Chennai,2023/10/13,2130.66,Grocery,3.4

In [ ]:
print(c.shape)

(140, 9)

In [ ]:
c.isnull().sum()

CustomerID          0
Name               10
Age                 6
Gender              7
City                6
JoinDate            9
PurchaseAmount      5
ProductCategory     4
Rating              7
dtype: int64

In [ ]:
c.duplicated().sum()

np.int64(16)

Removing Duplicate Rows

In [ ]:
c = c.drop_duplicates().reset_index(drop=True)
c

,CustomerID,Name,Age,Gender,City,JoinDate,PurchaseAmount,ProductCategory,Rating
0,118,Kiara Kumar,53,female,Chennai,11/01/2024,2625.28,FURNITURE,1.2
1,107,NaN,43,f,Banaras,2022/08/08,2954.49,Electronics,2.6
2,78,Saanvi Bose,45,male,HYDERABAD,20-Oct-2024,2984.16,electronics,3.7
3,93,ADITYA RAO,42,Male,Chennai,10-07-2021,1840.34,GROCERIES,1.0
4,18,Aadhya Singh,21,M,Mumbai,2024-08-14,3871.82,groceries,1.7
...,...,...,...,...,...,...,...,...,...
119,73,Aditya Bose,37,F,Hyderabad,09-Oct-2022,"₹3,708.85",Groceries,3.9
120,69,Riya Rao,57,Female,Banaras,2021-05-14,2763.77,Grocery,1.0
121,4,Arjun Iyer,NaN,female,BANGALORE,2024/12/15,"₹1,664.05",Groceries,3.8
122,120,MEERA MENON,33,NaN,HYDERABAD,2022-03-31,2575.75,Electronic,1.3
123,30,Ishaan Kumar,52,FEMALE,Chennai,2023/10/13,2130.66,Grocery,3.4

In [ ]:
c['Name'].isnull().sum()

np.int64(8)

Changing Name Column to Standardize Format and Filling Null Values

In [ ]:
c["Name"] = c["Name"].str.strip().str.title()
c["Name"] = c["Name"].fillna("Unknown")
c['Name']

0       Kiara Kumar
1           Unknown
2       Saanvi Bose
3        Aditya Rao
4      Aadhya Singh
           ...
119     Aditya Bose
120        Riya Rao
121      Arjun Iyer
122     Meera Menon
123    Ishaan Kumar
Name: Name, Length: 124, dtype: object

AGE

In [ ]:
c['Age'].isnull().sum()

np.int64(5)

In [ ]:
c['Age'].value_counts()

Age
50        7
39        5
25        4
56        4
43        4
53        4
33        4
42        3
57        3
45        3
31        3
20        3
59        3
18        3
23        3
19        3
34        3
24        3
35        3
62        3
19 yrs    2
49        2
22        2
52        2
58        2
37        2
51        2
30        2
59 yrs    2
38        2
61 yrs    1
29 yrs    1
21        1
60        1
32        1
47 yrs    1
28        1
55        1
-5 yrs    1
40        1
26        1
29        1
49 yrs    1
50 yrs    1
44        1
47        1
40 yrs    1
63        1
57 yrs    1
48        1
41        1
54        1
24 yrs    1
200       1
18 yrs    1
36 yrs    1
56 yrs    1
48 yrs    1
Name: count, dtype: int64

In [ ]:
c['Age'].replace("yrs","")
c['Age'] = pd.to_numeric(c['Age'], errors='coerce')
c.loc[c['Age'] < 0, 'Age'] = np.nan
c.loc[c['Age'] > 100, 'Age'] = np.nan

In [ ]:
c['Age']

0      53.0
1      43.0
2      45.0
3      42.0
4      21.0
       ...
119    37.0
120    57.0
121     NaN
122    33.0
123    52.0
Name: Age, Length: 124, dtype: float64

In [ ]:
mean = c['Age'].mean()
round(mean)

40

In [ ]:
c['Age'].fillna(round(mean), inplace=True)
c['Age']

0      53.0
1      43.0
2      45.0
3      42.0
4      21.0
       ...
119    37.0
120    57.0
121    40.0
122    33.0
123    52.0
Name: Age, Length: 124, dtype: float64

In [ ]:
c['Age'].value_counts()

Age
40.0    24
50.0     7
39.0     5
56.0     4
25.0     4
33.0     4
53.0     4
43.0     4
45.0     3
42.0     3
23.0     3
35.0     3
19.0     3
57.0     3
24.0     3
34.0     3
31.0     3
59.0     3
18.0     3
20.0     3
62.0     3
49.0     2
52.0     2
30.0     2
58.0     2
37.0     2
38.0     2
22.0     2
51.0     2
21.0     1
60.0     1
32.0     1
28.0     1
55.0     1
44.0     1
47.0     1
29.0     1
26.0     1
48.0     1
63.0     1
41.0     1
54.0     1
Name: count, dtype: int64

Gender

In [ ]:
c['Gender']

0      female
1           f
2        male
3        Male
4           M
        ...
119         F
120    Female
121    female
122       NaN
123    FEMALE
Name: Gender, Length: 124, dtype: object

In [ ]:
c['Gender'].value_counts()

Gender
FEMALE    18
M         16
male      13
female    13
f         12
MALE      10
F         10
m         10
Female     9
Male       6
Name: count, dtype: int64

In [ ]:
c.Gender= c.Gender.replace(['male','m','M','MALE'],"Male")
c.Gender= c.Gender.replace(['female','f','FEMALE','F'],"Female")
c.Gender

0      Female
1      Female
2        Male
3        Male
4        Male
        ...
119    Female
120    Female
121    Female
122       NaN
123    Female
Name: Gender, Length: 124, dtype: object

In [ ]:
c['Gender'].isnull().sum()

np.int64(7)

In [ ]:
c['Gender'] = c['Gender'].fillna("Not Identified")
c['Gender']

0              Female
1              Female
2                Male
3                Male
4                Male
            ...
119            Female
120            Female
121            Female
122    Not Identified
123            Female
Name: Gender, Length: 124, dtype: object

In [ ]:
c['Gender'].isnull().sum() # Now Null is 0

np.int64(0)

In [ ]:
c["Gender"].value_counts()

Gender
Female            62
Male              55
Not Identified     7
Name: count, dtype: int64

City

In [ ]:
c['City']

0        Chennai
1        Banaras
2      HYDERABAD
3        Chennai
4         Mumbai
         ...
119    Hyderabad
120      Banaras
121    BANGALORE
122    HYDERABAD
123      Chennai
Name: City, Length: 124, dtype: object

In [ ]:
c['City'].value_counts()

City
Chennai      7
kolkata      7
Calcutta     7
varanasi     6
Delhi        6
VARANASI     5
hyderabad    5
HYDERABAD    5
MUMBAI       5
Hyderabad    5
Banaras      5
Pune         4
Varanasi     4
new delhi    4
DELHI        4
Bombay       3
Madras       3
Kolkata      3
CHENNAI      3
KOLKATA      3
Mumbai       3
New Delhi    3
PUNE         3
chennai      3
mumbai       3
bangalore    2
Bangalore    2
BANGALORE    2
pune         1
bengaluru    1
delhi        1
Bengaluru    1
Name: count, dtype: int64

replace() = change values \
map() = convert values according to a mapping/dictionary.

In [ ]:
city_map = {
    "bombay": "Mumbai",
    "mumbai": "Mumbai",
    "calcutta": "Kolkata",
    "kolkata": "Kolkata",
    "madras": "Chennai",
    "chennai": "Chennai",
    "banaras": "Varanasi",
    "varanasi": "Varanasi",
    "bangalore": "Bengaluru",
    "bengaluru": "Bengaluru",
    "delhi": "Delhi",
    "new delhi": "Delhi",
    "hyderabad": "Hyderabad",
    "pune": "Pune",
}
c["City"] = c["City"].str.strip().str.lower().map(city_map)
c['City'] = c['City'].fillna("Unknown")
c['City']

0        Chennai
1       Varanasi
2      Hyderabad
3        Chennai
4         Mumbai
         ...
119    Hyderabad
120     Varanasi
121    Bengaluru
122    Hyderabad
123      Chennai
Name: City, Length: 124, dtype: object

In [ ]:
c['City'].value_counts()

City
Varanasi     20
Kolkata      20
Delhi        18
Chennai      16
Hyderabad    15
Mumbai       14
Pune          8
Bengaluru     8
Unknown       5
Name: count, dtype: int64

JoinDate

In [ ]:
c['JoinDate']

0       11/01/2024
1       2022/08/08
2      20-Oct-2024
3       10-07-2021
4       2024-08-14
          ...
119    09-Oct-2022
120     2021-05-14
121     2024/12/15
122     2022-03-31
123     2023/10/13
Name: JoinDate, Length: 124, dtype: object

In [ ]:
c['JoinDate'].isnull().sum()

np.int64(8)

In [ ]:
c['JoinDate'].value_counts()

JoinDate
12-11-2021     2
11/03/2024     2
2024/12/15     2
2023/12/09     2
10-07-2021     1
              ..
23/03/2024     1
09-Oct-2022    1
2021-05-14     1
2022-03-31     1
2023/10/13     1
Name: count, Length: 112, dtype: int64

In [ ]:
c.JoinDate = pd.to_datetime(c['JoinDate'], format = "mixed")
c.JoinDate

0     2024-11-01
1     2022-08-08
2     2024-10-20
3     2021-10-07
4     2024-08-14
         ...
119   2022-10-09
120   2021-05-14
121   2024-12-15
122   2022-03-31
123   2023-10-13
Name: JoinDate, Length: 124, dtype: datetime64[ns]

In [ ]:
c["JoinDate"].median()

Timestamp('2022-12-08 00:00:00')

In [ ]:
c["JoinDate"].fillna(c["JoinDate"].median(), inplace=True)
c["JoinDate"]

0     2024-11-01
1     2022-08-08
2     2024-10-20
3     2021-10-07
4     2024-08-14
         ...
119   2022-10-09
120   2021-05-14
121   2024-12-15
122   2022-03-31
123   2023-10-13
Name: JoinDate, Length: 124, dtype: datetime64[ns]

PurchaseAmount

In [ ]:
c['PurchaseAmount']

0        2625.28
1        2954.49
2        2984.16
3        1840.34
4        3871.82
         ...
119    ₹3,708.85
120      2763.77
121    ₹1,664.05
122      2575.75
123      2130.66
Name: PurchaseAmount, Length: 124, dtype: object

In [ ]:
c['PurchaseAmount'].isnull().sum()

np.int64(4)

In [ ]:
c['PurchaseAmount']= c['PurchaseAmount'].str.replace("₹","")
c['PurchaseAmount'] = c['PurchaseAmount'].str.replace(",","")
c['PurchaseAmount'] = c['PurchaseAmount'].astype(float)
c['PurchaseAmount']

0      2625.28
1      2954.49
2      2984.16
3      1840.34
4      3871.82
        ...
119    3708.85
120    2763.77
121    1664.05
122    2575.75
123    2130.66
Name: PurchaseAmount, Length: 124, dtype: float64

In [ ]:
c["PurchaseAmount"] = pd.to_numeric(c["PurchaseAmount"], errors="coerce")
c["PurchaseAmount"]

0      2625.28
1      2954.49
2      2984.16
3      1840.34
4      3871.82
        ...
119    3708.85
120    2763.77
121    1664.05
122    2575.75
123    2130.66
Name: PurchaseAmount, Length: 124, dtype: float64

In [ ]:
c["PurchaseAmount"] = (c["PurchaseAmount"].fillna(c["PurchaseAmount"].median()).round(2))
c['PurchaseAmount']

0      2625.28
1      2954.49
2      2984.16
3      1840.34
4      3871.82
        ...
119    3708.85
120    2763.77
121    1664.05
122    2575.75
123    2130.66
Name: PurchaseAmount, Length: 124, dtype: float64

ProductCategory

In [ ]:
c['ProductCategory']

0        FURNITURE
1      Electronics
2      electronics
3        GROCERIES
4        groceries
          ...
119      Groceries
120        Grocery
121      Groceries
122     Electronic
123        Grocery
Name: ProductCategory, Length: 124, dtype: object

In [ ]:
c['ProductCategory'].isnull().sum()

np.int64(4)

In [ ]:
c['ProductCategory'].value_counts()

ProductCategory
groceries      10
Book           10
BOOKS           9
Groceries       9
FURNITURE       8
Clothing        7
Electronics     7
Furniture       7
books           7
GROCERIES       7
clothing        6
Grocery         5
CLOTHING        5
furniture       5
ELECTRONICS     5
electronics     4
Apparel         3
Books           3
Electronic      3
Name: count, dtype: int64

In [ ]:
category_map = {
    "book": "Books",
    "books": "Books",
    "clothing": "Clothing",
    "apparel": "Clothing",
    "electronics": "Electronics",
    "electronic": "Electronics",
    "groceries": "Groceries",
    "grocery": "Groceries",
    "furniture": "Furniture",
}
c["ProductCategory"] = (
    c["ProductCategory"].astype(str).str.strip().str.lower().map(category_map)
)
c["ProductCategory"] = c["ProductCategory"].fillna("Other")
c['ProductCategory']

0        Furniture
1      Electronics
2      Electronics
3        Groceries
4        Groceries
          ...
119      Groceries
120      Groceries
121      Groceries
122    Electronics
123      Groceries
Name: ProductCategory, Length: 124, dtype: object

Rating

In [ ]:
c['Rating']

0      1.2
1      2.6
2      3.7
3      1.0
4      1.7
      ...
119    3.9
120    1.0
121    3.8
122    1.3
123    3.4
Name: Rating, Length: 124, dtype: float64

In [ ]:
c['Rating'].median()

3.0

In [ ]:
# Invalid ratings → NaN
c.loc[c["Rating"] > 5, "Rating"] = np.nan

# Fill missing ratings + round
c["Rating"] = c["Rating"].fillna(c["Rating"].median()).round(1)
c['Rating']

0      1.2
1      2.6
2      3.7
3      1.0
4      1.7
      ...
119    3.9
120    1.0
121    3.8
122    1.3
123    3.4
Name: Rating, Length: 124, dtype: float64

**Checking Cleaned Dataset**

In [ ]:
c.isnull().sum()

CustomerID         0
Name               0
Age                0
Gender             0
City               0
JoinDate           0
PurchaseAmount     0
ProductCategory    0
Rating             0
dtype: int64

In [ ]:
c

,CustomerID,Name,Age,Gender,City,JoinDate,PurchaseAmount,ProductCategory,Rating
0,118,Kiara Kumar,53.0,Female,Chennai,2024-11-01,2625.28,Furniture,1.2
1,107,Unknown,43.0,Female,Varanasi,2022-08-08,2954.49,Electronics,2.6
2,78,Saanvi Bose,45.0,Male,Hyderabad,2024-10-20,2984.16,Electronics,3.7
3,93,Aditya Rao,42.0,Male,Chennai,2021-10-07,1840.34,Groceries,1.0
4,18,Aadhya Singh,21.0,Male,Mumbai,2024-08-14,3871.82,Groceries,1.7
...,...,...,...,...,...,...,...,...,...
119,73,Aditya Bose,37.0,Female,Hyderabad,2022-10-09,3708.85,Groceries,3.9
120,69,Riya Rao,57.0,Female,Varanasi,2021-05-14,2763.77,Groceries,1.0
121,4,Arjun Iyer,40.0,Female,Bengaluru,2024-12-15,1664.05,Groceries,3.8
122,120,Meera Menon,33.0,Not Identified,Hyderabad,2022-03-31,2575.75,Electronics,1.3
123,30,Ishaan Kumar,52.0,Female,Chennai,2023-10-13,2130.66,Groceries,3.4

In [ ]:
c.to_csv("cleaned_data.csv", index=False)

In [ ]:
from google.colab import files
files.download("cleaned_data.csv")